name: Import PR Changes from xyz/repo1

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number from xyz/repo1'
        required: true
        default: '96'

jobs:
  import-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo PR
        uses: actions/checkout@v4
        with:
          repository: unify-apps/deutsche-telekom-env
          token: ${{ secrets.GT_TOKEN_PR }}
          path: temp-repo
          fetch-depth: 0
          
      - name: Clone source PR repository
        env:
          GH_TOKEN: ${{ secrets.GT_TOKEN_PR }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/unify-apps/deutsche-telekom-env.git temp-repo
          temp-repo
          cd temp-repo
          gh pr checkout ${{ github.event.inputs.pr_number }}
          cd ..

      - name: Copy changes
        run: |
          rsync -av --exclude='.git' temp-repo/ ./

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b import-pr-${{ github.event.inputs.pr_number }}
          git add .
          git commit -m "Import changes from xyz/repo1 PR #${{ github.event.inputs.pr_number }}"
          git push origin import-pr-${{ github.event.inputs.pr_number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Import changes from xyz/repo1 PR #${{ github.event.inputs.pr_number }}
          title: Import PR #${{ github.event.inputs.pr_number }} from xyz/repo1
          body: |
            This PR imports changes from xyz/repo1 PR #${{ github.event.inputs.pr_number }}.
          base: main
