on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number from xyz/repo1'
        required: true
        default: '96'

jobs:
  import-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination (abc) repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone source (xyz) repo PR branch
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GH_PAT_SOURCE }}@github.com" > ~/.git-credentials
      
          git clone https://github.com/unify-apps/deutsche-telekom-env.git source-repo
          cd source-repo
          git fetch origin pull/${{ github.event.inputs.pr_number }}/head:pr-${{ github.event.inputs.pr_number }}
          git checkout pr-${{ github.event.inputs.pr_number }}
          cd ..

      - name: Copy code from source PR
        run: |
          rsync -av source-repo/ . --exclude '.git' --exclude '.github'

      - name: Commit and push to a new branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b import-pr-96
          git add .
          git commit -m "Import changes from PR #96 of sunil-sirvi repo"
          git push https://x-access-token:${{ secrets.GH_PAT_DEST }}@github.com/unify-apps/deutsche-telekom-env.git import-pr-96

      - name: Create PR to main branch
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT_DEST }}
          commit-message: Import PR #96 from sunil-sirvi repo
          title: Import PR #96 from xyz repo
          body: Pulling changes from PR #96 from https://github.com/unify-apps/deutsche-telekom-env (sunil-sirvi)
          base: main
          branch: import-pr-96
